name: Sync fork with upstream

permissions:
  contents: write

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/OCA/web.git || true
          git fetch upstream --prune

      - name: Sync all branches
        run: |
          for branch in $(git branch -r | grep upstream/ | grep -v HEAD | sed 's|upstream/||'); do
            echo "Processing branch: $branch"
          
            # Skip branches with workflow files
            if git ls-tree -r upstream/$branch | grep -q '.github/workflows/'; then
              echo "Skipping $branch because it contains workflows"
              continue
            fi
          
            if git show-ref --verify --quiet refs/heads/$branch; then
              git checkout $branch
              git merge --ff-only upstream/$branch || true
            else
              git checkout -b $branch upstream/$branch
              git push -u origin $branch --force-with-lease   # push new branch immediately
            fi
          done

      - name: Push changes
        run: git push origin --all --force-with-lease
